### PR TITLE
Data boxinfo

### PR DESCRIPTION
**Pull request by Rand3rino**

### CODE REVIEW

**Comment by SimonOyen** [comment]
@Rand3rino Marcus made some changes to the API, so that's why the test fails. We could either merge this and fix everything after that, or make the fixes, merge that into this branch and make sure everything works.

I think the 2nd way would be the professional one, but the project is small enough to do it the first way. What do you think?

**Comment by Rand3rino** [comment]
I agree that with you that we should do it the second way.

**Review by SimonOyen — CHANGES_REQUESTED** [review]
We will make some changes to the API connection before this request gets merged.

* [ ] In the box list only box-previews should be used (should be faster and require less bandwidth).

**Comment by Rand3rino** [comment]
Merging the data-inspection branch into this one first. Do not review yet

**Comment by Rand3rino** [comment]
Ready for review

**Review by SimonOyen — APPROVED** [review]
Nice work! :+1:

**Pull request merged**
